### ISSUE TITLE
Support repository creation

### ISSUE THREAD

**Issue by bentinata** [zaquestion/lab#113]

**Comment by zaquestion** [comment]
This one will break falling through to hub since `hub create` and `lab create` would conflict and there isn't a straightforward way ( that I can think of ) do detect which the user wants. That said, I'll implement soon and hub users can call hub explicitly for repo creation. It shouldn't be that big a deal since creating repos is a less frequent operation.

**Comment by zaquestion** [comment]
@bentinata I coded up some initial support for this as `lab repo create` (alias `lab project create`). I still need to add some tests and address some known edge cases, but should be able to get this out in the `0.10` release targeted for this week.

**Comment by bentinata** [comment]
@zaquestion Thanks for your effort into this. Really appreciated.

**Comment by zaquestion** [comment]
@bentinata [v0.10](https://github.com/zaquestion/lab/releases/tag/v0.10.0) is released
```
lab project create [path]
# or 
lab repo create [path]
```
