### ISSUE TITLE
labels in issues

### ISSUE THREAD

**Issue by qazip** [zaquestion/lab#122]
Hello,

I've just recently installed lab and I'm wondering how to approach labels in issues. Is there a flag to do stuff by label? For example, how does one:

- Search by label?
- Add issue with label?

**Comment by zaquestion** [comment]
Hi @qazip,

Lab currently supports lists issues and merge requests by label(s)
Example for issues:
```
lab issue list --label bug
# multi label
lab issue list --label feature --label server
```
Ref: https://zaquestion.github.io/lab/lab_issue_list.html

Currently label isn't supported during create, shall I consider this an official request? I have a release planned for this week, I can possibly sneak this in should be a small change. Otherwise I'll get it into the next

**Comment by qazip** [comment]
Yes, please! Adding labels when creating is extremely important to me.

**Comment by zaquestion** [comment]
@qazip [v0.10](https://github.com/zaquestion/lab/releases/tag/v0.10.0) is released

**Comment by zaquestion** [comment]
Example
```
lab issue create -l bug -l critical -m "big bad issue"
```
