### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by lasselindqvist** [zaquestion/lab#157]
I see hub supports Windows and has installation instructions, but apparently lab does not. Any plans about this?

**Comment by zaquestion** [comment]
No specific plans, there's at least one thing that needs to change on the internals around `stat`ing files or something. 

Goreleaser can be used to release to chocolatety. Largely I recommend using the Linux subsystem for Windows which works really well

**Comment by tydavis** [comment]
From what I can tell, with the removal of some dependencies (which still do things like execute external commands for things handled under https://golang.org/pkg/os/ ), the Stat-ing of files is OS-independent and other routines should be 100% usable.  

Otherwise, I think we only need a beta-tester to confirm our fixes are "correct"

**Comment by tydavis** [comment]
@zaquestion I'd say try it first and see -- I've used `exec` and similar on windows without any consequences.  

As for the hub changes, the windows-specific modifications are for console-specific bits and ancillary pieces (ensuring a URL is not a windows path). Nothing to worry about, I don't think.

**Comment by zaquestion** [comment]
@lasselindqvist @tydavis I released some windows binaries in the last release (`0.12.0`), if you try them out please let me know if they work!

**Comment by zaquestion** [comment]
Tried out `lab 0.12.0` on my Windows 10 box and it seems to work.
- `lab ci view` doesn't work in `git shell` due to "unsupported character set". It worked in powershell, but the screen refreshes were a little gross, overall the functionality seemed to work.
- listing mrs and issues worked fine
- creating a merge request seemed to work
  - vim was unable to create swap file for MERGEREQ file, however didn't block anything.

I'll get windows supported in the install script, try to get it into a package manager, and update the install docs.

**Comment by lasselindqvist** [comment]
I tried using with Windows 7 and basic command line. Basic functionality seems to be working fine, but I don't really have anything to test with currently, so I cannot vouch for everything.

**Comment by zaquestion** [comment]
Added scoop and basic windows instructions in: https://github.com/zaquestion/lab/pull/200

**Comment by cmorty** [comment]
Adding documentation about using scoop with https://github.com/zaquestion/scoop-bucket without filling the repo it is very confusing. ;) (Yes I know, bad timing.)

**Comment by zaquestion** [comment]
Ugh, I know, I really should just put the damn release out :) "just one more thing"

**Comment by zaquestion** [comment]
@cmorty Okay, I got out of bed and finished the `v0.13.0` release, I'm going to close out this issue now, but I'd appreciate if you could let me know if the scoop instructions work. I've never used it myself and don't have great access to a windows box to test it right now.

**Comment by cmorty** [comment]
@zaquestion Seems to work. I do have some other issues, but these do not seem to be windows and definitely not scoop-realted.
 I'm unsure whether it would be a good idea to add a `scoop update` before installing. But this is the first time I work with scoop, so I do not feel in the position to judge.
