### ISSUE TITLE
"lab create" = "hub create" when hub installed

### ISSUE THREAD

**Issue by d33tah** [zaquestion/lab#163]
When both `lab` and `hub` are installed, `lab create` actually runs `hub create`. This is super confusing - any chance you could make `lab XYZ` not try calling `hub XYZ`?

**Comment by tydavis** [comment]
Maybe we should [stop integrating with hub][1].

[1]:https://github.com/zaquestion/lab#hub--lab--hublab

**Comment by d33tah** [comment]
I would MUCH prefer it to also follow `hub`'s conventions. I don't mind `lab` having their own ones, but it would in my opinion help Gitlab adoption to have predictable CLI tools - even if you only just installed it.

**Comment by zaquestion** [comment]
The approach I'm thinking right now is to stop having `lab` passthrough for this case. I agree its easy to run into and end up creating a github repo when you wanted a gitlab one. Since repo create is likely to be less frequent than other operations it seems fine to insist users call hub directly.

**Comment by zaquestion** [comment]
@d33tah I've put up 2 PRs in an effort to address this issues. The first #167 removes the hub integration, the later #168 only prevents passthrough for the `hub create` command. Any preference from your side?

**Comment by d33tah** [comment]
TBH, neither. I would prefer `lab create` to have same semantics as `hub create`, only for Gitlab. Thanks for writing the project, but you might have hard time pleasing me by introducing a new convention :"P

**Comment by zaquestion** [comment]
@d33tah I'm hesitant, to allow `lab create` to work because it would break this passthrough to lab. We talked about this a bit when originally adding the feature https://github.com/zaquestion/lab/issues/113#issuecomment-370133273

Am interested in hearing your case, be aware lab hasn't "follow convention" for a some time. For a while the expectation was that hub would be moving in a similar direction (`cmd NOUN VERB`, see `hub pr`). lab does this to be inline with GitLabs documentation/API and aim to be discover-able. 

While lab started out with the goal of being true to `hub`, this is no longer the case. In order to take advantage of GitLab's offering and provide a clean API we've somewhat departed from that goal.

How does `lab create` serve you better than `lab project create`? Workflow is very important to us and drives virtually every decision made for lab.

**Comment by d33tah** [comment]
@zaquestion It boils down to remembering things. Alternatively I would love to migrate to whatever is the alternative to`hub` that follows your syntax. Otherwise, I need to remember both and I don't use those tools often enough for it to become natural quickly, so it might be frustrating.

**Comment by zaquestion** [comment]
@d33tah In that case, I'll go ahead with #168 which prints a warning when using `lab create` and informs the user to call hub directly or use the lab equivalent. I'll try to be mindful when adding future commands to minimize confusion. It's still important to me that its easy to migrate/adopt `hub` -> `lab`. I'll leave this issue open until I've had a chance to audit the other lab/hub commands for similar confusion. `lab browse` for instance should probably get the same treatment.

**Comment by zaquestion** [comment]
Personally I'm still getting a lot of utility around passing through hub commands so I'd like to keep that in where it works (not this case)

**Comment by d33tah** [comment]
That's a pretty good compromise - having messages that remind of proper usage would be helpful.

**Comment by zaquestion** [comment]
Released changes to prevent passthrough of `lab browse` and `lab create` with help messages in `0.12.0`
