### ISSUE TITLE
Make "lab project create" default to creating a project with CWD's name

### ISSUE THREAD

**Issue by d33tah** [zaquestion/lab#164]
Compare to `hub create`. I would expect `mkdir xyz && cd xyz && lab project create` to create `xyz` project, like `hub create` does.

Also note that `lab project create .` fails with the following:

```
2018/06/11 10:12:46 projectCreate.go:37: POST https://gitlab.com/api/v4/projects: 400 {message: {base: [Unable to save project. Error: Name can contain only letters, digits, emojis, '_', '.', dash, space. It must start with letter, digit, emoji or '_'.]}, {limit_reached: []}, {name: [can contain only letters, digits, emojis, '_', '.', dash, space. It must start with letter, digit, emoji or '_'.]}}
```

**Comment by d33tah** [comment]
It's not about `lab project create`, but `lab create` which is not defined in `lab`, so it falls back to `git`, which runs `hub`.

**Comment by zaquestion** [comment]
@d33tah It sounds like #163 is the main issue. I'm going to close out this issue and focus on discussion on the #163, please reopen if I'm misunderstanding the situation.

Just to really hammer the `lab project create` command here. This `lab project create` should behave a expected above sans `.` 

`[path]` below is probably confusing, because it refers to the desired gitlab project path (similar to name, but distinct in the API). It does NOT refer to a local path. I'll try to make that clearer in the docs.
```
$  lab project create -h
If no path or name is provided the name of the git repo working directory

Usage:
  lab project create [path] [flags]

Flags:
  -d, --description string   description to use for the new project
  -h, --help                 help for create
  -n, --name string          name to use for the new project

```
