### ISSUE TITLE
Use JSON for config instead of HCL

### ISSUE THREAD

**Issue by tydavis** [zaquestion/lab#165]
Reasoning:

- HCL requires a dependency, JSON does not.
- JSON is complex enough (and human-readable enough) to handle all of our use cases

>A little copying is better than a little dependency.

https://go-proverbs.github.io/

**Comment by bmeneguele** [comment]
IMHO, today we don't really need to worry too much about a dependencies when they are small enough for the storage space and internet speed we have :).
But, due to real issues with Viper's HCL parser, we had to change from HCL to TOML, dropping the additional dependency.

The reason for which we changed to TOML instead of JSON, or even YAML, was the similarity of it compared to the git config file. We wanted to keep lab config file format close to how git config looks like, so people familiar with Git only (and not too much with JSON and/or YAML) wouldn't feel too uncomfortable with the new format.
