### ISSUE TITLE
Add additional validation when creating merge requests

### ISSUE THREAD

**Issue by zaquestion** [zaquestion/lab#20]
I've run into 2 cases where lab permitted creating an MR when it really shouldn't have.
- source branch was not present on source remote (creates an MR with an unavailable branch)
- source branch is already up to day with target
  - observed when forgetting to commit changes and starting an MR

**Comment by bmess** [comment]
I observed the first bullet point this evening.  I don't think it's the fault of the tool, but perhaps it would provide expected behavior of it checked for the source branch to exist.  

I think automatically pushing the branch could be dangerous, but maybe if it's not force pushed?  I'm not sure. 

Just a warning from the MR creation that source branch doesn't exist & and exit might be enough. Maybe include a flag to automatically push the branch if it doesn't exist, as long as it's up to the user to do the override from the less dangerous behavior of a push without alerting.

**Comment by zaquestion** [comment]
Tempted to change the defaults when I fix this as well. Currently lab assumes origin/upstream if the branch doesn't point to its remote. Perhaps the forked remote should be the default which would likely reduce the chances of hitting this case entirely.

**Comment by zaquestion** [comment]
Bullet point 1 fixed in `0.5.2`

**Comment by bmeneguele** [comment]
Bullet point 2 fixed in `0.22.0` by 4f8cc175dd6443cc2182455e948079fc7fe25413.
