### ISSUE TITLE
`lab issue search`

### ISSUE THREAD

**Issue by magiraud** [zaquestion/lab#208]
A command could list issues using the `search` attribute of the API.

**Comment by magiraud** [comment]
Or it could be a flag to `lab issue list`.

**Comment by claytonrcarter** [comment]
I like the idea of doing this via `lab issue list --search`, though I'm not sure what to do about a short flag as `-s` is already taken by `--state`.

@zaquestion if you're open to this, I would be happy to submit a PR.

**Comment by zaquestion** [comment]
I tend to think search should come in as a positional argument, but I don't fully understand why I think this to begin with...

I would accept `lab issue list [remote [search]]` for sure. Otherwise, I'd like to hear rational to do so differently and in turn see `lab project list [search]` updated to match.

**Comment by claytonrcarter** [comment]
This was merged in #242.
