### ISSUE TITLE
Project overlap, differences from lighttiger2505/lab

### ISSUE THREAD

**Issue by bzub** [zaquestion/lab#220]
Hi, thanks for working on this gitlab CLI project! I find it very useful, especially the forking and git wrapping features.

I'm curious how the design or roadmap of this project compares to [lighttiger2505/lab](https://github.com/lighttiger2505/lab)? I'd like to contribute to one of these projects but I'm not sure which one. Thanks again.

BTW, I opened a similar ticket in the other project: https://github.com/lighttiger2505/lab/issues/65

**Comment by zaquestion** [comment]
Sorry for the late reply here I've been battle with a nasty cold all weekend.

I can outline some of the differences and where this tool is headed.

## Differences

Feature wise it looks like lighttiger's lab supports some operations with project variables and projects users that we don't

Over here it looks like we have forking, a CI pipeline interface, and job tracing.

## Design 

As @lighttiger2505 mentions, we have different command structure. We strictly use `lab <noun> <verb>` whereas lighttigers tool uses `lab <verb>` or `lab <noun>` as needed.

zaquestion/lab was initially designed to be a `hub` replacement for gitlab. We used to follow the conventions there much closer, but have since decided to move in our own direction. Firstly with our strict command structure, then by supporting `origin` or `upstream` remote schemes, now going beyond hub features to support more features like the CI pipeline interface which wouldn't make sense in hub.

zaquestion/lab is fundamentally workflow tool. We don't add features just to cover the API. We add them to support and improve our cli workflows. 

## Roadmap

For 1.0 there are a few things we'd like to do. The next "big thing" is an MR review workflow for the CLI. An outline can be seen here: https://github.com/zaquestion/lab/projects -- I see you're interested in supporting comments on MRs (and issues) thats going to be an early part of this project covered in https://github.com/zaquestion/lab/issues/83

We will also be removing the hub/git wrapper aspect of the project and moving to use git extensions in https://github.com/zaquestion/lab/issues/217

We may change the `lab mr create` syntax https://github.com/zaquestion/lab/issues/127

The config structure is very likely to change, at least to support https://github.com/zaquestion/lab/issues/151

**Comment by bzub** [comment]
Thanks for the detailed overview! Hopefully I can contribute in the near future.

**Comment by varac** [comment]
It would be nice to mention the existance of lighttiger2505/lab in the README.md together with the differences.

And why you don't work together to produce an even more feature complete tool, because both have features that the other doesn't and that's a pity !

**Comment by zaquestion** [comment]
@varac what would detailing differences between the tools in the readme serve to achieve? I'm open to referencing `lighttiger2505/lab` in something like a similar tools section and evwn indicating briefly why one might prefer his their tool to this one, but that's about it.

No reason not to work together really, currently the tools take different approaches and I believe both started as hobby projects meant to serve the founders objectives. 

lighttiger highlights some of the advantages of labs command structure (cobra),  it's possible lab could support both syntaxes with minimal work and functionality could be consolidated.

This is appealling to me as it would serve to unify the communities and pave way to the ultimate goal of becoming an officially regconized tool with GitLab

**Comment by varac** [comment]
> what would detailing differences between the tools in the readme serve to achieve?

I.e., if I would have known that this project currently doesn't support multiple instances (#151), and `lighttiger2505/lab` does, I would have taken `lighttiger2505/lab`. However, I'm super happy about `lab ci trace`, and there might be other features that are better in this project, so it would be just good for users to know what to choose.

> I'm open to referencing lighttiger2505/lab in something like a similar tools section and even indicating briefly why one might prefer their tool to this one, but that's about it.

That's fine.

> This is appealling to me as it would serve to unify the communities and pave way to the ultimate goal of becoming an officially regconized tool with GitLab

Woooo ! That would be really great !
