### ISSUE TITLE
lab project list shows other users' projects

### ISSUE THREAD

**Issue by simonmichael** [zaquestion/lab#235]
Thanks for lab! After configuring an old but still valid personal access token that I think is correct (I only have one), `lab project list` lists 100 projects belonging to other people (and not mine). Is this expected ?

**Comment by zaquestion** [comment]
@simonmichael That's expected. `lab project list` used to default to only your projects and that's why the description says "list your projects". It looks like when the command was updated I forgot to update the description.

You can limit to your projects with
`lab project list --mine`
https://zaquestion.github.io/lab/lab_project_list.html

I'll leave this issue open as an item to update the docs

**Comment by claytonrcarter** [comment]
@zaquestion is there a way to change the default behavior of `lab project list` to only show "my projects". I'm having a hard time thinking of when I would ever want to get a list of all public repos. It makes sense from an API perspective, but feels counter-intuitive from a user tool perspective.

**Comment by zaquestion** [comment]
For historical reference the change in defaults came out of https://github.com/zaquestion/lab/issues/185

It was more about making interactions with the number of results make sense less so about whose projects. 

I'm a little cautious to change the default outright, but would consider it if there was enough interest (thumb up the issue if you like it folks!)

Regarding setting your own defaults, that's something I'd love to support and have wanted since the beginning of lab. Ideally I'd like to allow options in the config to set this values and will definitely be something that's addressed with the upcoming config overhaul

**Comment by zaquestion** [comment]
It's worth noting the current behavior favors self hosted instances. The primary usecase I had in mind when adding the command was searching for   repos in your organization. Since then people have been using it for all sorts of cases and I'm honestly not sure what it should do.

For instance, personally I'm not sure why I'd list my own repos, but I could definitely see listing repos I'm a member of. I'm curious to hear what folks are doing with it and how it fits into their workflow

**Comment by simonmichael** [comment]
Here's my experience, FWIW: 
hub is great, should I have this lab thing ? Oh brew install ? Ok then. Is it working - I wonder if I can list my projects. lab. Nice, gitlab commands at the end. In addition to the github commands, neat. Some of those commands overlap, I wonder how that works out. project looks like a possibility. lab project. "list  List your projects", excellent. lab project list. Hmm.. unexpected: a large unordered list of random users and projects, not including me. Is there a problem with my access token ? Should I be seeing these projects ? Are my private projects exposed ? Is gitlab's API buggy ? Is this software buggy ? Is it listing all projects on gitlab ? Wouldn't that be a much longer list ? Any reports of this in the issue tracker ? No. Do I want this tool enough to report it ? No.. oh alright then. (I haven't read the docs and didn't think to try lab project --help.)

**Comment by simonmichael** [comment]
PS:
Alright then, listing all projects would be kind of cool, can it do that ? lab project list -n 100000 | wc -l ... hmm, still running 10 minutes later. Ctrl-C. lab project list -n 1000  ... seems hung as well ? No, just slow (1m).

**Comment by bmeneguele** [comment]
After commit 47de8c5fc8fae5410daee363c33216799f68db32 (v0.18.0) was merged, it's now possible to set default values for any command option, meaning that:
```
[project_list]
mine = true
```
in lab's config file will force `lab project list` to always present the projects from myself only.
For getting back the default behavior you can either remove the config entry or run `lab project list --mine=false`.

@simonmichael @claytonrcarter does that solve the concerns raised here?

**Comment by claytonrcarter** [comment]
I think the current behavior makes sense for self hosted instances, but not at all for instances like gitlab.com. That said, if BC is a concern, then yes that totally makes sense to set default values for commands. Thanks.

**Comment by bmeneguele** [comment]
Yeah, I'm not 100% fan of BC tbh :), but considering we this option set like that since 2018 (almost completing 3years) I prefer to not flip the behavior completely. So lets keep it as is for now.
