### ISSUE TITLE
Support old GitLab v3 API

### ISSUE THREAD

**Issue by spidey** [zaquestion/lab#247]
I'm stuck using a corporate GitLab install that is extremely outdated and currently only supports the v3 API. Is it possible to make lab work with it?

**Comment by claytonrcarter** [comment]
I not an expert here, but I would say "Not easily" and probably just "No". lab uses go-gitlab to make the API calls, which dropped support for v3 sometime last year. You could try building lab yourself with the last version of go-gitlab that supported v3, but it's possible that it might not even build as the go-gitlab API has probably changed since then, and you would be on your own for testing as most of the tests use gitlab.com which hasn't supported the v3 API for some time now. go-gitlab has [a note in their docs](https://github.com/xanzy/go-gitlab#note) about how to find the last version that supported v3.

**Comment by spidey** [comment]
I was afraid the answer would be in this line, that it would be too much effort to support a deprecated API version. Too bad.

Also I've seen that upgrading GitLab, if it wasn't installed through the OmniBus package, will take a lot of effort, since it has been a while and lots of versions has been released between 8.0.5 and the latest version.

**Comment by zaquestion** [comment]
@spidey don't give up hope, upgrading GitLab is achievable! If you run into any problems and need help feel free to toss them here and maybe we can pitch in. I want everyone to be able to use lab and upgrading is best route.
