### ISSUE TITLE
Feature Request:  option to have URL for merge request with diff

### ISSUE THREAD

**Issue by bmess** [zaquestion/lab#26]
Generally I tend to submit links to my team with the URL provided by the `merge-request` tool, but append `/diffs` to the end.

It'd be nice to have it automatically appear that way based on the user's config file.

## I get:
https://gitlab.com/example/my_project/merge_requests/100
## I'd like
https://gitlab.com/example/my_project/merge_requests/100/diffs

**Comment by zaquestion** [comment]
Couple thoughts:
* We currently don't have any non `git config` based config. Which is nice because it keeps labs operations simply. Cobra makes it pretty easy to add "persistent flags" which are config file based. I'd be interested in exploring that sometime as cases like these start to build up.
* Personally, I'd be fine changing the default functionality to give you the diff url instead. This way the user can copy whichever section they want.

**Comment by bmess** [comment]
Took me long enough!
