### ISSUE TITLE
lab ci view fails

### ISSUE THREAD

**Issue by MartinDelille** [zaquestion/lab#268]
Since I updated `lab` with `brew`, `lab ci view` fails:

```
2018/12/19 16:40:45 ci_view.go:481: <nil>
```

For information:

```
$ lab version
git version 2.17.2 (Apple Git-113)
hub version 2.5.0
lab version master
```

**Comment by MartinDelille** [comment]
I re-cloned the source with `go get github.com/zaquestion/lab` and checked out the last release. 

The problem is still there but I'm not sure if I really compiled it well.

Could you tell me how to do so so I try to debug it myself?

**Comment by zaquestion** [comment]
Usually this happens when the pipeline can't be found. I'd try explicitly specifying the remote you'd like to search. `lab ci view origin` for example. If you find the pipeline that way, it might point to some funky behavior selecting the remote.

There was a change a while back where we updated the pipeline search to match the branch. Before this change it was possible to get a stale pipeline and not actually the one related to the tip of what you're working on. I'd double check the branch <> pipeline combination in the GitLab UI as well to make sure you weren't hitting that case before.

**Comment by MartinDelille** [comment]
Fixed with the latest version.
