### ISSUE TITLE
Setting just LAB_CORE_HOST does nothing

### ISSUE THREAD

**Issue by mpickering** [zaquestion/lab#269]
I have set `LAB_CORE_HOST` to the correct URL for our project but the program still prompts for the gitlab host on the first run. It seems that unless all three variables are set then the others are ignored.

**Comment by zaquestion** [comment]
@mpickering This is correct, lab needs all 3 values to operate. If it can't find them and the config file doesn't exist it assumes it needs to prompt you for the values. You're correct that lab ignores the variables in this case.

I think theres a case to be made that we should only require host and user since for public uses I believe we don't need the token. I'm not sure what the request here is though.. What would you like lab to do differently?

**Comment by mpickering** [comment]
I intended to wrap the executable so that our users would only have to provide their token. The wrapper would set `LAB_CORE_HOST` and then call `lab` like normal. 

What is the username used for btw? Is the token on its own not sufficient?

**Comment by zaquestion** [comment]
You're probably right, these requirements are from the earliest days of lab. Its probably just an API call to get the username, so we probably only need the token. Lab uses it largely for searching and naming remotes

**Comment by zaquestion** [comment]
Will definitely check it out, and contributions welcome.

We can change the creds logic to not prompt if we already have an environment variables set.

**Comment by zaquestion** [comment]
@mpickering I've made some changes to remove the need to set the username explicitly and have lab use `LAB_CORE_HOST` to skip prompting for a host on first setup. 

I'll get it merged in this week. There are a few other items in the next milestone and I'd like to see if I can get a few more in, but I'll try and do a release this week since theres a good amount in it.

**Comment by zaquestion** [comment]
@mpickering I've release this functionality in `0.15.0`
