### ISSUE TITLE
Unable to create merge-request: mr_create.go:105: gitlab project not found

### ISSUE THREAD

**Issue by fuzzyweapon** [zaquestion/lab#282]
This likely occurs because the repo name is strange.
I was able to `lab fork foo/SomeHorribleRepoName.com`
I was able to push.
But then, when I tried `lab merge-request` I got...
`mr_create.go:105: gitlab project not found`

Likewise `lab mr list` gives the same error.

I don't have control over the server as I'm a contractor hitting an internal instance over vpn.  If this is because of the `.` character in the repo name, I realize the handling responsibility shouldn't traditionally be on lab to do it.

However, from a user perspective, it feels reeeeally off that one can successfully do some stuff, but not others when the main entry point (in terms of user scenario) for working with lab starts with commands that will work (i.e. `lab clone ...` and `lab fork ...`).

At the very least, it would be nice to have a check for this problem that occurs when using those "entry point" commands that warns the user if they hit this scenario.

**Comment by zaquestion** [comment]
Improving lab's error messaging in the case where we don't have access would be great. Due to the way gitlab's API works, its intentional that you can't tell the difference between `project not found` and access denied for many calls. This is a security precaution to prevent bad actors from determining what repos a private group has.

That said there may be a way to have lab check against a particular endpoint to validate authentication. In the case of subgroups tho, I think this is next to impossible. That said we could always update the error message to say `gitlab project not found, verify you have access to the requested resource" or some such

**Comment by varac** [comment]
Improving this would be a great UX improvement, given [all these issue reports](  https://github.com/zaquestion/lab/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+gitlab+project+not+found). I stepped into this myself for one project, whereas antoher project works.
