### ISSUE TITLE
Document that `lab project browse` depends on a remote named `origin`

### ISSUE THREAD

**Issue by jkleckner** [zaquestion/lab#284]
My colleague was able to perform `lab project browse` and have the project name discovered automatically but this didn't work for me and required specifying an explicit remote.  After digging around, I found out that my pattern is to not use a remote named `origin` in favor of more explicit names for remotes, specifically the namespace.

It would be very nice to document this dependence on `origin`.  And for double bonus points, use the upstream remote for the branch that I am on.

**Comment by zaquestion** [comment]
Can definitely update lab project browse to use the upstream remote. This is how `lab mr create` works should be pretty easy to beef up other commands. Admittedly lab likes to rely expected remote names like origin/upstream/[user]

**Comment by jkleckner** [comment]
That would be great, thanks!

**Comment by aboyett** [comment]
Would it make sense to allow the user to specify a "default remote" in the lab.hcl config to support workflows where the user prefers a remote other than "origin" or "upstream"?

**Comment by jkleckner** [comment]
@aboyett is that instead of or in addition to the remote, if it exists, for the current branch?

**Comment by zaquestion** [comment]
The upstream `-u` remote should always take too priority, regarding guessing I'm open to supporting a config value atop The logic to select origin/upstream/[user]

**Comment by aboyett** [comment]
@zaquestion's last comment matches my thoughts. The config option would only be used in situations where the current logic would default to "origin" or "upstream". A tracked remote (`-u`) would take precedent if it exist. I think should a config option would make it easier to adopt workflows where the user desires the default remote to be something other than "origin" or "upstream"

**Comment by zaquestion** [comment]
@jkleckner to @aboyett's point I've found using the tracked remote as a hard and fast rule to be more troublesome than expected. Since the user may use apply the tracked remote to a fork and intend to MR against a different remote. In implementation I opt'd to compromise on using the remote tracked by master, which I suspect to reflect the `forkedFromRemote`.

https://github.com/zaquestion/lab/pull/287

@jkleckner I'm curious if this implementation works for you? The logic will intend impact `lab project browse` in the way you wanted if you set the remote on master. I'm also curious if the below block with selecting the `forkRemote` should be the USER or `origin` in your usecase? (see https://github.com/zaquestion/lab/pull/287/files#diff-ff7686b39bf90dc2520886fb874371a4R234)

**Comment by jkleckner** [comment]
@zaquestion Sorry to take so long to reply.  This code does handle my use case as the remote of master *is* does represent the upstream project namespace.

Thanks!

**Comment by bmeneguele** [comment]
It should be now solved by MR !438.
Feel free to reopen this issue in case it doesn't help your use case.
