### ISSUE TITLE
lab is Slow 

### ISSUE THREAD

**Issue by luisdavim** [zaquestion/lab#292]
Hi,

I use git bash prompt as my prompt and today I gave it a try to alias lab as git and immediately I've noticed a major slow down every time I hit return. I also have hub installed and I've also tryed aliasing hub as git and didn't experienced the same issue. 

I used brew to install both lab and hub.

**Comment by zaquestion** [comment]
@luisdavim This isn't lost on me, and needs to be addressed, I'll try to look into it before the next release. In the meantime there are a few things you can try which should help.

- Upgrade to the latest version of lab (may have improvements depending on your current version)

- Use unaliased git in your git_prompt functions (generally recommended). Mine look like this:
```
git_branch()
{
	if ! $(which git) rev-parse --git-dir > /dev/null 2>&1; then
		return 0
	fi

	echo $($(which git) branch 2>/dev/null| sed -n '/^\*/s/^\* //p')
}

git_prompt ()
{
	if ! $(which git) rev-parse --git-dir > /dev/null 2>&1; then
		return 0
	fi

	echo "($(git_branch))"
}
# export all these for subshells
export -f git_prompt
export PS1="\u@\h:\w \[\033[m\]\$(git_prompt)\n\$ "
```

- Use git aliases instead of aliasing lab to git
https://git-scm.com/book/en/v2/Git-Basics-Git-Aliases
This is the long term vision for lab, and I intend to make it the the sole way of aliasing with lab come 1.0

**Comment by prarit** [comment]
@luisdavim is this still an issue?

**Comment by prarit** [comment]
I'm going with "this is no longer a problem" :).  Please reopen if this is still an issue.

**Comment by zaquestion** [comment]
Yeah, I believe we've addressed various slowdown cases resulting from aliasing at this point.
