### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by ShalokShalom** [zaquestion/lab#310]
Your installation section in the readme tells me to do: ```git clone git@github.com:zaquestion/lab```

Which asks me for a fingerprint and then tells me: ```Permission denied```

```git clone https://github.com/zaquestion/lab``` does work indeed.

**Comment by ShalokShalom** [comment]
Another Documentation issue: 

The Readme tells me that lab will ask me for my credentials. That is true, although the second line does not come up. Nonetheless, how to input my password?

```lab``` happens to give me a 401, no further information.

**Comment by ShalokShalom** [comment]
Is there any documentation at all? Nor ```lab help``` neither ```man lab``` helps me further. 

I know this is all your project, which you do in your spare time, so take this all as a friendly feedback. 

Thanks a lot :hugs:

**Comment by claytonrcarter** [comment]
You can try `lab --help`. Each of the subcommands has pretty good help text, which is accessible via `--help`: so `lab ci --help`, `lab issue create --help`, etc.

I'll leave your other questions for Zaq to tackle.

**Comment by ShalokShalom** [comment]
I have tried lab --help. It just throws me the same error message.

**Comment by zaquestion** [comment]
@ShalokShalom Could you post the error you are seeing? I've seen some recent changes in the gitlab api and its possible some ux has degraded. Regarding your initial issue with `git` the fact that `git clone` worked over https vs ssh really indicated an issue with your ssh configuration. Make sure your public key is attached to a github accout for clones. Likewise you'll want to have a working ssh configuration with lab as it makes heavy use of that protocol.

If you're having trouble accessing documentation through the tool, we have the documentation hosted here: https://zaquestion.github.io/lab/

> That is true, although the second line does not come up. Nonetheless, how to input my password?
Just to be sure we're on the same page, when inputing your api key the credentials will be masked so you will not seem them entered on the terminal for security purposes.

P.S. Thanks @claytonrcarter nice to see you around, I've finally getting out from underwater with the day job, should have a bit more time to tend this garden soon :D

**Comment by ShalokShalom** [comment]
There is no ssh configuration on my side. Your documentation says zero about this requirement. 

![Screenshot_20190517_121326](https://user-images.githubusercontent.com/6344099/57921243-353e8880-789d-11e9-9bac-938ca441fa5e.png)

>  Just to be sure we're on the same page, when inputing your api key the credentials will be masked so you will not seem them entered on the terminal for security purposes.

No. It does not come up at all. It simply skips the whole line. 

Here is the error message: 

```2019/05/17 12:15:58 main.go:118: GET https://gitlab.com/api/v4/user: 401 {message: 401 Unauthorized}```

**Comment by zaquestion** [comment]
Are you using the latest version of lab, somewhere in `0.14.x` I believe there is a bug that checks to aggressively for the username from the api. I would check if a `~/.config/lab.hcl` got created with bad data. In the worst case, you should at least be able to hand write the config and get going. 

Happy to help troubleshoot this with you and get you going. That said, lets temper some of the expectations here.

By default, I expect users of lab to have a basic understanding of git. Further you are expected to know how to operate git for your repos without `lab`. `git@github.com:<user>/<repo>` is syntax (scp style) for ssh, we don't document "ssh configuration to github is required to pull repo over ssh using these install steps" because it should be evident in the steps. 

If you're struggling to clone `git` repos from GitHub, you might find challenges integrating a `git` workflow extension like `lab`. Encourage you to reflect on the oweness when you're throwing around statements like 
>  Your documentation says zero about this requirement.
If we can't expect our users to know how to clone a git repo, documentation for a tool around git workflows suddenly becomes challenging, there would simply be too many cases where basic concepts need to be broken down causing docs to be overly expository. 

Now all that said, I'm happy to support you and make lab more accessible through easier documentation. The lab community is committed to getting every user up and running, and iterating on the tool.

**Comment by ShalokShalom** [comment]
Well, I have pulled your master, so I should be on the newest version. 

I honestly think that the lack of documentation should simply be fixed by "ssh token on Github" in the requirement section. Everyone has its own workflow and in all those hundreds of pull requests and issues I had raised up, I had zero occasions like that. So its obviously a rare edge case and I guess you dont know 100% of Git either. I have never bothered setting ssh up and this is the first instruction in about a hundred of repos which requires this. 

So thanks for your help.
