### ISSUE TITLE
lab ci view does not render if "only: merge_requests"  a.k.a merge_request_pipelines is used 

### ISSUE THREAD

**Issue by lukmdo** [zaquestion/lab#338]
`lab ci view` does not render merge_request_pipelines (ones using `only: merge_requests`) 
https://docs.gitlab.com/ee/ci/merge_request_pipelines/

```
$ lab ci view
2019/10/03 19:10:54 ci_view.go:484: <nil>

$ lab version 
git version 2.22.0
hub version 2.12.1
lab version 0.16.0
```

I created two branches 
1. https://gitlab.com/lukmdo/test/tree/test_merge_request_pipelines corresponding to MR 
https://gitlab.com/lukmdo/test/merge_requests/1
which generates two pipelines 
- branch pipeline https://gitlab.com/lukmdo/test/pipelines/86375805
- merge requests pipeline labeled as `detached` https://gitlab.com/lukmdo/test/pipelines/86375806
when run `lab ci view` this only renders `branch pipeline`  
<img width="199" alt="Screen Shot 2019-10-03 at 7 22 29 PM" src="https://user-images.githubusercontent.com/87109/66153599-bcee1f00-e613-11e9-95cd-97b80d8c0e14.png">

that is ~OK however **expected** latest (merge requests pipeline in this case) would be rendered

2. https://gitlab.com/lukmdo/test/tree/check_only_merge_request_pipelines corresponding to MR 
https://gitlab.com/lukmdo/test/merge_requests/2 
which generates only 
- merge requests pipeline labeled as `detached` https://gitlab.com/lukmdo/test/pipelines/86378820
when run `lab ci view` this fails 
```
$ lab ci view
2019/10/03 19:10:54 ci_view.go:484: <nil>
```
**expected** rendered merge requests pipeline with two jobs 

See all pipelines https://gitlab.com/lukmdo/test/pipelines

**Comment by zaquestion** [comment]
I suspect this has to do with how lab selects the pipeline to render, before `merge_request` pipelines you could get away with only rendering the branch pipeline because there was no difference (and the same pipeline was displayed on the MR anyhow). 

Here's what the pipelines look like from your test repo (thanks for putting that together)
```
[
  {
    "id": 86378820,
    "sha": "2710a09d5ed85b1414c5cee5af50f3bd587bd9f5",
    "ref": "refs/merge-requests/2/head",
    "status": "success",
    "created_at": "2019-10-03T18:10:22.873Z",
    "updated_at": "2019-10-03T18:12:31.483Z",
    "web_url": "https://gitlab.com/lukmdo/test/pipelines/86378820"
  },
  {
    "id": 86375806,
    "sha": "c2ff4ceff3fe4a20d54ef27038151e64c3578979",
    "ref": "refs/merge-requests/1/head",
    "status": "success",
    "created_at": "2019-10-03T17:54:41.275Z",
    "updated_at": "2019-10-03T17:55:35.817Z",
    "web_url": "https://gitlab.com/lukmdo/test/pipelines/86375806"
  },
  {
    "id": 86375805,
    "sha": "c2ff4ceff3fe4a20d54ef27038151e64c3578979",
    "ref": "test_merge_request_pipelines",
    "status": "success",
    "created_at": "2019-10-03T17:54:41.135Z",
    "updated_at": "2019-10-03T17:55:36.495Z",
    "web_url": "https://gitlab.com/lukmdo/test/pipelines/86375805"
  },
  {
    "id": 86373764,
    "sha": "63cce1d06a53dfb29f18d1e96944904f912ddbf0",
    "ref": "test_merge_request_pipelines",
    "status": "success",
    "created_at": "2019-10-03T17:42:38.053Z",
    "updated_at": "2019-10-03T17:46:32.270Z",
    "web_url": "https://gitlab.com/lukmdo/test/pipelines/86373764"
  }
]
```

I used to have the logic work against the sha, and changed it to use the ref due to some flakyness IIRC. It's probably worth attempting to return to that method since it looks like it would select the right pipeline in those cases.

**Comment by zaquestion** [comment]
This is the code that does that, a pretty easy change would be to add logic above to get the sha out of the branch and then use that as the filter. I believe the function itself used to accept a sha and I'm thinking I only changed it because you could use ref and it made things easier. So if we just do the lookup in that function it's still simplified for the callers and hopefully resolves the issue

https://github.com/zaquestion/lab/blob/master/internal/gitlab/gitlab.go#L625-L627

**Comment by lukmdo** [comment]
nice @zaquestion this indeed should be small change that way.
If that helps I might get get this a go over weekend and see if can submit PR.

**Comment by zaquestion** [comment]
@lukmdo Sounds good, I can definitely review and bring it in, and if so commit to making the time to get the release out. ATM I've just started a new job (it's my first week!) so it's been a little hectic between finishing out the last and now onboarding at the new. I haven't had time to give lab the attention it needs recently, any help you can offer us is greatly appreciated.

**Comment by johnwebbcole** [comment]
Any progress on fixing this?

**Comment by lukmdo** [comment]
I check and back to this this week - looking to this after long while.

**Comment by zaquestion** [comment]
@lukmdo does #380 solve this issue?

**Comment by prarit** [comment]
No answer to @zaquestion request for feedback on #380.  Closing this out.
