### ISSUE TITLE
Error at first usage : unsupported protocol scheme ""

### ISSUE THREAD

**Issue by alaenix** [zaquestion/lab#365]
Hello,

I installed lab on Ubuntu 18.04.3 LTS using the curl installation command but after i gived my gitlab account id and token, I got this error message each time I'm trying to use lab :

`2020/02/13 11:36:17 main.go:178: Get myname@domain.com/api/v4/user: unsupported protocol scheme ""`

`lab -h` and `lab version` are giving me the same error.

Any ideas how to fix that ?

Thanks in advance !

**Comment by claytonrcarter** [comment]
Best guess: you need to edit your gitlab host to start with`https://`. (I'm also not sure how it handles `user@host` format, so that may be another issue.) I forget if there's a way to "reconfigure" lab after the first time, but you can manually edit your settings in `~/.config/lab.hcl`. (Well, that's where it is for me, on a mac.)

**Comment by alaenix** [comment]
@claytonrcarter Thanks for the respond. Modifying directly the `~/.config/lab.hcl` worked for me :

```
"core" = {
  "host" = "https://gitlab.com"

  "token" = "myGitlabApiToken"
}
```

I figured this out by myself ultimately but I struggled with this issue because there is no way to "reconfigure" lab after the first time and it seems broken (inability to use -h or version options).

**Comment by zaquestion** [comment]
The attempt to simplify configuration by looking to the user from the API, while nice, has left a number of usability issues like the one you encountered here truth be told
