### ISSUE TITLE
lab mr create: mr_create.go:83: exit status 129

### ISSUE THREAD

**Issue by yoctocell** [zaquestion/lab#366]
# Problem
I  have two branches - `master` and `test` and I am trying to create a merge request to merge `test` into `master`:

```
lab mr create
```
But I get the following error:

```
mr_create.go:83: exit status 129
```

# System
- OS: Arch linux
- git version: 2.25.0
- lab version: 0.17.2

How should I fix this?

Thanks!

**Comment by bmeneguele** [comment]
I'm not being able to reproduce the issue.
There were some changes in the last few weeks, could you retest it?

**Comment by zaquestion** [comment]
@yoctocell Sorry you're having issues getting going with lab.

The issue you're running into seems to be related to looking up your local git config. The particular call that's failing is a lookup the remote in your `.git/config`. If you want to paste that hear we can try and offer additional insights, otherwise there are a few scenarios:
Regarding which source remote lab will try to lookup.
1. If the branch is tracked by a remote; uses that remote `branch.<name>.remote`
2. Else if a remote with the username is present use that (user's fork)
3. Else if `origin` refers the the user's fork (`upstream` remote in use) use `origin`

It's weird that you'd run into an error at this particular line, but I'd guess there's some wonkiness with the how the remotes are setup.

Ref: https://github.com/zaquestion/lab/blob/a7646da14338df8cdaabc2a9f80c45d47c2bd322/cmd/mr_create.go#L81-L84

**Comment by yoctocell** [comment]
Sorry, forgot about this issue as I am no longer using gitlab.
