### ISSUE TITLE
hardcoded remote discovery for working tree commands

### ISSUE THREAD

**Issue by bmeneguele** [zaquestion/lab#438]
There are situations where the clone or fork process isn't done via the lab tool, but the user wants to use it regardless, thus the remote being used by the user may not follow the pattern that the lab tool uses: `upstream`, `origin` or `lab.User()`.
```
$ git remote -v
origin-2        git@gitlab.com:bmeneg/Test-Lab.git (fetch)
origin-2        git@gitlab.com:bmeneg/Test-Lab.git (push)
$ lab mr list
2020/09/25 17:45:11 mr_list.go:36: the key `remote.origin.url` is not found
```
However, some commands accept the `[remote]` positional arg:
```
$ lab mr list origin-2
#2 fix test file
```
Those commands that perform remote operations (based on the Gitlab library) they work based on the project name, so they are fine most of the cases (didn't test all of them).
However, those commands that interact with the local/working tree get lost:
```
$ lab mr checkout 2
2020/09/25 17:58:18 mr_checkout.go:36: the key `remote.origin.url` is not found
$ lab mr checkout origin-2 2
fatal: 'origin' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
2020/09/25 17:58:24 mr_checkout.go:79: exit status 128
```
IIUC (and, please, correct me if I'm wrong) these commands rely on the information held in the `forkedFromRemote` (and `forkRemote` (?)) internal vars, which are always set to one of the options: `origin` or `upstream` (and `lab.User()` for `forkRemote` ), which doesn't seem to be the best approach, considering the users may choose different naming convention.

A way of solving it would be to rework the way `forkedFromRemote` gets set, by also considering/checking the current remote being tracked by the current branch before settling on `origin`. Another point I need some lights on is on the usage of `forkRemote`, that I didn't really understand.

**Comment by zaquestion** [comment]
Bit of a brain dump... bare with me.

The primary purpose of `forkRemote` and `forkFromRemote` are to add the needed context for a few different types of scenarios, mostly around choosing the right default remote for a command:
1. Creating merge requests, in the absence of the branch being tracked, lab can make the assumption that you want to create a merge request from your fork to the original. Might be some other cases like this too
2. `forkRemote` doesn't get much usage, it merely returns as a default in the case the branch doesn't track a remote in https://github.com/zaquestion/lab/blob/8955ade8557ce30125c21d24fd689f7861c41df7/cmd/mr_create.go#L231-L239
`determineSourceRemote` is only using in `mr create` and `ci run`
3. `forkedFromRemote` would be chosen as the default for listing issues/merge requests


There's some nuance around `forkedFromRemote` that makes using the tracked branch as an override here not suitable. Theres a thread that gets into it a bit here https://github.com/zaquestion/lab/issues/284#issuecomment-462100859

The comment here is misleading https://github.com/zaquestion/lab/blob/master/cmd/root.go#L269-L273
> 		// use the remote tracked by the branch if set

What is meant is "use the remote tracked by the *default branch*" if set, which obviously is a relic of assuming that would be `master`. This logic should ideally use the default branch for the repo, which is a bit tricky since it precedes knowing the gitlab project (as the `forkedFromRemote` logic is a part of making that determination). This would improve the determination logic, but wouldn't solve for the `lab mr checkout` case. 

In `lab mr checkout`s case, I overlooked that even tho we'd look up the MR on the passed in remote we don't fetch from that remote https://github.com/zaquestion/lab/blob/master/cmd/mr_checkout.go#L78 -- so this should really be overridden by the remote that got passed in.

Another improvement we could make to `forkedFromRemote` might be to have a final fallthrough case it choses the first remote in the list (I believe the remotes can be returned in the same order as they are in the `.git/config`), in the event `origin`/`upstream` don't exist. That said, if we can work out a way to get the defaultBranch and lookup the remote for that, I reckon that would obviate the need for this case altogether.

**Comment by zaquestion** [comment]
I put up https://github.com/zaquestion/lab/pull/441/files to address the MR checkout issue, which I tested with a similar repo setup to what you showed here.

**Comment by bmeneguele** [comment]
> I put up https://github.com/zaquestion/lab/pull/441/files to address the MR checkout issue, which I tested with a similar repo setup to what you showed here.

Just tested and it indeed works :). :+1: 

> 2. `forkRemote` doesn't get much usage, it merely returns as a default in the case the branch doesn't track a remote in `determineSourceRemote` is only using in `mr create` and `ci run`

That's one of the reasons I thought on removing it and use forkedFromRemote. Although I'm still confused by the code (where each are eactually used) I think I got the idea. One thing I didn't have in my mind, but after reading the issue #284 I realized is the fact the code is built with `origin|upstream|lab.User()` in mind... it wasn't meant to be generic at first.

At the same time, the following code:
https://github.com/zaquestion/lab/blob/97ffd5e67c15895adc2c9b48afe93d43918c65d1/cmd/root.go#L268-L274
is never really hit, since `forkedFromRemote` is never really set to `""`. With that, `master`'s tracked remote (git's `-u`) is not considered for e.g. `mr create`. I'm going to reuse the MR #440 for getting it correct.

Thanks for the explanation @zaquestion !

**Comment by bmeneguele** [comment]
> Another improvement we could make to forkedFromRemote might be to have a final fallthrough case it choses the first remote in the list (I believe the remotes can be returned in the same order as they are in the .git/config), in the event origin/upstream don't exist.

Unfortunately, that's not the case: `git remote` prompt remotes in alphabetical order. I agree that the first remote in the .git/config may be the best choice for the 'main remote', so I'm going to check a way of doing so and also check:

> That said, if we can work out a way to get the defaultBranch and lookup the remote for that, I reckon that would obviate the need for this case altogether.

**Comment by bmeneguele** [comment]
@zaquestion I've updated MR #440 with new patches for handling most of what we've talked about here.

**Comment by bmeneguele** [comment]
Considering the MR #440 and others that landed after we can close this issue.
