### ISSUE TITLE
how to install lab in centos?

### ISSUE THREAD

**Issue by guaizi149** [zaquestion/lab#601]
how to install lab in centos?

- centos7.2

**Comment by bmeneguele** [comment]
Hi @guaizi149 , unfortunately, you can't build it in centos 7 due to Golang compiler version and other dependencies lacking.
Because of that, I've been keeping a non-official repository that you can use for downloading a pre-compiled (CentOS 7 and 8) version of it.
https://copr.fedorainfracloud.org/coprs/bmeneguele/rhkernel-devtools/

I'm going to update to v0.20.0 in a few hours.

**Comment by guaizi149** [comment]
Thank you very much!
