### ISSUE TITLE
'lab mr create' failed to create a valid merge request

### ISSUE THREAD

**Issue by snitm** [zaquestion/lab#635]
I made my changes to a local branch, pushed the changes to my clone hosted on gitlab, my branch's changes needed to be merged into my remote origin's main branch, so from my local workspace on my branch I ran: lab mr create

lab dutifully showed my changes:

```
# Requesting a merge into origin:main from origin:update_dm_raid (1 commits)
#
# Write a message for this merge request. The first block
# of text is the title and the rest is the description.
#
# Changes:
#
# d362ff5 (Mike Snitzer)
#    owners.yaml: remove section for dm-raid, it is covered by DM subsystem
#
#  info/CODEOWNERS    |  3 ---
#  info/RHMAINTAINERS |  5 -----
#  info/owners.yaml   | 10 ----------
#  3 files changed, 18 deletions(-)

```
But upon closer inspection of above, lab is mistaken to think the changes I want merged reside at 'origin:update_dm_raid'

Here are 2 failed merge requests that I created (meant to be against 2 different branches on my snitm remote):
https://gitlab.com/redhat/rhel/src/kernel/documentation/-/merge_requests/24/diffs
https://gitlab.com/redhat/rhel/src/kernel/documentation/-/merge_requests/25/diffs

It wasn't until I went to my cloned repo's branch and used the gitlab UI to create the MR that gitlab did the right thing:
https://gitlab.com/snitm/documentation/-/tree/update_dm_raid_v2
https://gitlab.com/redhat/rhel/src/kernel/documentation/-/merge_requests/26/diffs

So I'm left entirely confused and completely unsure what I am doing wrong, or how to make 'lab mr create' work as I've experienced it able to do in the past (given my same exact workflow). HELP! ;)

**Comment by prarit** [comment]
@snitm could you run 'history' and cut-and-paste the EXACT commands you executed?

**Comment by snitm** [comment]
> @snitm could you run 'history' and cut-and-paste the EXACT commands you executed?

OK, but please don't think less of me! ;)

```
 1274  git remote update
 1275  git log
 1276  git checkout -b update_dm_raid origin/main
 1277  emacs -nw owners.yaml
 1278  git diff
 1279  ls
 1280  cat ../README.md
 1281  pwd
 1282  cd ..
 1283  make
 1284  git diff
 1285  git log
 1286  git push snitm update_dm_raid

<like an idiot I forgot to 'git commit -a'>

 1287  lab mr create
 1288  git log
 1289  git commit -a
 1290  git log
 1291  fg
 1292  git push snitm update_dm_raid
 1293  lab mr create
 1294  lab mr help
 1295  lab mr -h
 1296  lab mr --mine
 1297  lab mr list --mine
 1298  lab mr reopen 23

<I hoped that reopening would kick gitlab to pick up the new 'snitm:update_dm_raid' contents.. it didn't so I fumbled with trying to rebase my open MR... that failed horribly.. 'lab mr rebase' is _still_ a mystery to me!>

 1299  lab mr rebase 23
 1300  lab mr rebase -h
 1301  git branch
 1302  lab mr rebase update_dm_raid 23
 1303*
 1304  lab mr rebase snitm update_dm_raid
 1305  lab mr rebase snitm/update_dm_raid 23
 1306  lab mr rebase snitm 23
 1307  lab mr close 23

<so I gave up on MR 23>

 1308  git push snitm update_dm_raid
 1309  ls -ltr
 1310  ls -ltr .*
 1311  cat .gitlab-ci.yml
 1312  ls -ltr .*
 1313  cat .git/COMMIT_EDITMSG
 1314  rm .git/COMMIT_EDITMSG
 1315  rm .git/*~
 1316  lab mr create
 1317  git remote --delete snitm update_dm_raid

<prarit told me to run that, look wrong, but I tried it.. he meant 'git push ...', anyway, I deleted remote branch with following>

 1318  git push snitm :update_dm_raid
 1319  git branch -m update_dm_raid update_dm_raid_v2
 1320  git log
 1321  git push snitm update_dm_raid_v2
 1322  lab mr create -h
 1323  lab mr create
 1324  git log
 1325  lab mr create -h
 1326  git remote -v
 1327  rpm -q lab
 1328  yum install lab

<I already have the latest lab rpm: lab-0.20.0-1.el7.x86_64 >
```

I then decided to try the gitlab web UI, worked fine (as I detailed in my initial report aboce).

**Comment by prarit** [comment]
>  1276  git checkout -b update_dm_raid origin/main

The problem here is that you've declared a branch with the default remote set to upstream (ie, the default remote of update_dm_raid is origin/main).  The default remote and branch takes precedence in the code so it's always going to point to origin/main instead of snitm/main.

Now I'm scratching my head why the UI works :)

**Comment by snitm** [comment]
> > 1276  git checkout -b update_dm_raid origin/main
> 
> The problem here is that you've declared a branch with the default remote set to upstream (ie, the default remote of update_dm_raid is origin/main). The default remote and branch takes precedence in the code so it's always going to point to origin/main instead of snitm/main.
> 
> Now I'm scratching my head why the UI works :)

If that is _the_ reason _this_ is why I'm not a fan of git meta-tools (github or gitlab)... they are being far too "cute" about inferring what is being requested to be merged.

The way I created my branch in 100% standard git usage.  There isn't some extra meaning behind it.. I used origin/main as the starting point of my branch.  I made changes.  Those changes are to be merged to origin/main (which I branched from). 

So please explain to me again why the merge request via 'lab mr create' would draw the conclusion: "origin:update_dm_raid is to be merged into "origin/main" if "origin" (aka gitlab.com:redhat/rhel/src/kernel/documentation.git) doesn't actually _have_ a branch named update_dm_raid?

**Comment by snitm** [comment]
(btw, my workflow on all gitlab MR have started with branching with "git checkout -b <mybranch> origin/<branch>" so for it to suddenly not be acceptable is kind of strange)

**Comment by bmeneguele** [comment]
Hi @snitm,

we have two improvements here:

1. (lab side) adding `--source-branch` is something indeed we should do, so the user can make sure the right branch is being used; even a `--source-remote` is valid, considering the input for `lab mr create` is `<target-remote> <target-branch>`, so yes, we're going to consider implementing it.
2. (user side) you can add a best-practice step to your workflow: get used to use the `-u` (or `--set-upstream`) option during `push`, e.g. `git push -u snitm update_dm_raid`, it'll re-target your current working branch to track `snitm/update_dm_raid` instead of `origin/main`.

Let me give you some additional context on why 2) is important (you may even already know, sorry if I'm being too verbose) and may help avoid some mistakes:
When you called `git checkout -b update_dm_raid origin/main` you explicitly told git that you wanted your brand new branch to track the `main` branch from `origin` remote, but when you wanted to push the changes that you've done in that working branch you didn't want to directly push to `origin/main`, which would be the default action in case you've called a simple `git push` (git would _guess_ that you wanted to push the changes to the tracking `origin/main` pair), but you want to push to `snitm/update_dm_raid` and for that it would be wise to drop the "tracking" status from `origin/main` and add it to `snitm/update_dm_raid` to avoid mistakes. That's where you call `git push` with the `-u` (or `--set-upstream`) option set.

lab follows/mimic the same preference list as git in this case: use the "tracking remote and branch" pair if it's set.  That's why your use case failed and also why `lab` was (erroneously) able to find into `origin` the `update_dm_raid` branch: it actually used the tracking remote and branch (found into `origin` the `main` branch).

Item 1) allow users to avoid such mistakes, but won't prevent users not using 1) with the wrong tracking pair.
We can also add a warning message to the user that "something _might_ be wrong" in case the tracking pair mismatch somehow with other infos we have, but still, lab follows the same approach as git in this case.

**Comment by prarit** [comment]
So after looking at things, I also agree there's a mistake @snitm made:  he should have done a 'git push -u' not a 'git push' *as the documentation clearly states*.  Having said that, I don't think having a --set-upstream is entirely a bad idea.  I would prefer that users use 'push -u' but not against a --set-upstream.  We've added other options like it (to do git-ish things in lab).  I am going to think about bailing if the resulting MR has 0 commits.  That should never happen and at least be a warning to others that they did something wrong.

**Comment by prarit** [comment]
I'll fix the 0 commits issue in !637.

**Comment by snitm** [comment]
> Hi @snitm,
> 
> we have two improvements here:
> 
> 1. (lab side) adding `--source-branch` is something indeed we should do, so the user can make sure the right branch is being used; even a `--source-remote` is valid, considering the input for `lab mr create` is `<target-remote> <target-branch>`, so yes, we're going to consider implementing it.

Would think it best to provide --source remote:branch
_And_ --dest remote:branch

> 2. (user side) you can add a best-practice step to your workflow: get used to use the `-u` (or `--set-upstream`) option during `push`, e.g. `git push -u snitm update_dm_raid`, it'll re-target your current working branch to track `snitm/update_dm_raid` instead of `origin/main`.

But I really don't want my current working branch to track the remote, I want it tracking 'origin/main'
This use of git push's -u to hack in hints that makes lab mr create's guesswork more informed is a poor solution/recommendation.

I have a fundamental problem with the notion that my local branch will then be left tracking a remote I happened to push my local branch to.  It makes no sense on a functional workflow level for that branch to track that remote.

> 
> Let me give you some additional context on why 2) is important (you may even already know, sorry if I'm being too verbose) and may help avoid some mistakes:
> When you called `git checkout -b update_dm_raid origin/main` you explicitly told git that you wanted your brand new branch to track the `main` branch from `origin` remote, but when you wanted to push the changes that you've done in that working branch you didn't want to directly push to `origin/main`, which would be the default action in case you've called a simple `git push` (git would _guess_ that you wanted to push the changes to the tracking `origin/main` pair), you wanted to push to `snitm/update_dm_raid` and for that you explicitly told git it by calling `git push snitm update_dm_raid`. Likewise, it would be wise to drop the "tracking" status from `origin/main` and add it to `snitm/update_dm_raid` to prevent git from _guessing_ something wrong. That's where you call `git push` with the `-u` (or `--set-upstream`) option set.

I never rely on git guessing _anything_.

> lab follows/mimic the same preference list as git in this case: use the "tracking remote and branch" pair if it's set. That's why your use case failed and also why `lab` was able to (erroneously) "find" into `origin` the `update_dm_raid` branch: it actually used the tracking remote and branch (found into `origin` the `main` branch).
> 
> Item 1) allow users to avoid such mistakes, but won't prevent users not using 1) with the wrong tracking pair.
> We can also add a warning message to the user that "something _might_ be wrong" in case the tracking pair mismatch somehow with other infos we have, but it would be another _guess_.

But it is a "wrong tracking pair" from your gitlab-focused workflow.  From a developer perspective, my local branch tracking its upstream is most effective for how I've become accustomed to using git.

The fact that some people see power in a simple commandline shows how we're likely doomed for giving users a very cutthroat default interface/experience.

That said, maybe I've been "doing git wrong" forever... I just kind of balk at that given all that I've been tasked with doing in the context of being an upstream Linux subsystem maintainer. *shrug*

**Comment by bmeneguele** [comment]
> Would think it best to provide --source remote:branch

That's valid for sure!

> _And_ --dest remote:branch
> 

Not sure about it, `lab mr create` already has as positional args the `target` remote and branch.
Reworking positional args would make sense if all commands were reworked, requiring a major change in the project. And, at the same time, I don't think it's desirable. So, for now, we should consider `--source` only.

> > 1. (user side) you can add a best-practice step to your workflow: get used to use the `-u` (or `--set-upstream`) option during `push`, e.g. `git push -u snitm update_dm_raid`, it'll re-target your current working branch to track `snitm/update_dm_raid` instead of `origin/main`.
> 
> But I really don't want my current working branch to track the remote, I want it tracking 'origin/main'
> This use of git push's -u to hack in hints that makes lab mr create's guesswork more informed is a poor solution/recommendation.
> 
> I have a fundamental problem with the notion that my local branch will then be left tracking a remote I happened to push my local branch to. It makes no sense on a functional workflow level for that branch to track that remote.
> 
> > Let me give you some additional context on why 2) is important (you may even already know, sorry if I'm being too verbose) and may help avoid some mistakes:
> > When you called `git checkout -b update_dm_raid origin/main` you explicitly told git that you wanted your brand new branch to track the `main` branch from `origin` remote, but when you wanted to push the changes that you've done in that working branch you didn't want to directly push to `origin/main`, which would be the default action in case you've called a simple `git push` (git would _guess_ that you wanted to push the changes to the tracking `origin/main` pair), you wanted to push to `snitm/update_dm_raid` and for that you explicitly told git it by calling `git push snitm update_dm_raid`. Likewise, it would be wise to drop the "tracking" status from `origin/main` and add it to `snitm/update_dm_raid` to prevent git from _guessing_ something wrong. That's where you call `git push` with the `-u` (or `--set-upstream`) option set.
> 
> I never rely on git guessing _anything_.
> 
> > lab follows/mimic the same preference list as git in this case: use the "tracking remote and branch" pair if it's set. That's why your use case failed and also why `lab` was able to (erroneously) "find" into `origin` the `update_dm_raid` branch: it actually used the tracking remote and branch (found into `origin` the `main` branch).
> > Item 1) allow users to avoid such mistakes, but won't prevent users not using 1) with the wrong tracking pair.
> > We can also add a warning message to the user that "something _might_ be wrong" in case the tracking pair mismatch somehow with other infos we have, but it would be another _guess_.
> 
> But it is a "wrong tracking pair" from your gitlab-focused workflow. From a developer perspective, my local branch tracking its upstream is most effective for how I've become accustomed to using git.
> 

I understand your point of view, however, what I've always used and understood from git's manpage I think the description I gave is the actual intent. `git-push` manpage is too shallow about the intent of the option, `branch.<name>.merge` in `git-config` is mentioned for "more detailed explanation". 

Lets forget about `lab` now and also the fork-workflow, which isn't the git default workflow: what I understand as "tracking upstream" for git is the remote relative of my local branch, to where I want to push my changes and where I want to pull from new changes, this is the usual branch-workflow. 

In the fork-workflow the meaning of the option doesn't change: you're still pushing and pulling to your private fork, the "upstream project" is something else that, in my view, isn't covered by any `git-push` options and, because of that, I have to change my daily git workflow a bit (it has been the workflow I've seen with many other developers working under fork-workflow projects):
1. I have one local branch dedicated to tracking the "upstream project" master/main branch, where I keep pulling new changes;
2. when some work must be done I create a new branch (`git checkout -b <newbranch> <upstream-main-branch>`), following almost the same steps you did, but without informing the `<remote>`;
3. in the push step I basically set `-u` telling git what's the relative remote branch of this local branch I'm working at.

> The fact that some people see power in a simple commandline shows how we're likely doomed for giving users a very cutthroat default interface/experience.
> 

It's pretty hard to define the "limits" a tool can go, there are many different types of users, but even then `lab` does nothing more than parse/filter/handle GitLab API queries and responses and, hopefully, present the results in a somewhat comfortable way. IMHO that's the least opinionated this tool can be. I agree 100% with you about the "branch" guessing though, we should stop trying to go further, and it's now on my TODO list to add the `--source` opt :).

> That said, maybe I've been "doing git wrong" forever... I just kind of balk at that given all that I've been tasked with doing in the context of being an upstream Linux subsystem maintainer. _shrug_

I understand your view and it makes sense. I don't think it's wrong. Just the use case might be slightly different :).

**Comment by snitm** [comment]
> > Would think it best to provide --source remote:branch
> 
> That's valid for sure!
> 
> > _And_ --dest remote:branch
> 
> Not sure about it, `lab mr create` already has as positional args the `target` remote and branch.
> Reworking positional args would make sense if all commands were reworked, requiring a major change in the project. And, at the same time, I don't think it's desirable. So, for now, we should consider `--source` only.

OK.

> I agree 100% with you about the "branch" guessing though, we should stop trying to go further, and it's now on my TODO list to add the `--source` opt :).

Sounds good, and thanks for all your other helpful comments!
