### ISSUE TITLE
`git fork` where `origin` is the fork doesn't add `upstream`

### ISSUE THREAD

**Issue by zaquestion** [zaquestion/lab#78]
Instead a new remote pointing to the fork gets added.
*actual*
```
origin git@gitlab.com:lab-testing/test
lab-testing git@gitlab.com:lab-testing/test
```
*expected*
```
origin git@gitlab.com:lab-testing/test
upstream git@gitlab.com:zaquestion/test
```

**Comment by ianfoo** [comment]
Can you clarify this issue a bit? It is written from the context of someone familiar with the project and this problem. What does "where origin is the fork" mean, exactly? What is the meaning of "upstream" here? I can tell why the remotes under *actual* seem wrong, since it's the same remote with two names, but I cannot tell why the remotes under *expected* are right. Who is the user you've run the fork command as--zaquestion? And if so why would you expect the remote to be called `upstream` instead of `zaquestion`?

For background, when using **hub**, I have typically cloned the origin of a project, and when I do a `git fork`, I expect my user to be the name of the new remote, as shown here:
```
➜  github.com git clone zaquestion/lab zaquestion/lab
Cloning into 'zaquestion/lab'...
remote: Counting objects: 3323, done.
remote: Compressing objects: 100% (31/31), done.
remote: Total 3323 (delta 8), reused 4 (delta 1), pack-reused 3291
Receiving objects: 100% (3323/3323), 8.69 MiB | 6.13 MiB/s, done.
Resolving deltas: 100% (1066/1066), done.
➜  github.com cd zaquestion/lab
➜  lab git:(master) git fork
Updating ianfoo
From git://github.com/zaquestion/lab
 * [new branch]      ci         -> ianfoo/ci
 * [new branch]      issue40    -> ianfoo/issue40
 * [new branch]      master     -> ianfoo/master
 * [new branch]      mrEdit     -> ianfoo/mrEdit
new remote: ianfoo
➜  lab git:(master) gr -v
ianfoo	git@github.com:ianfoo/lab.git (fetch)
ianfoo	git@github.com:ianfoo/lab.git (push)
origin	git://github.com/zaquestion/lab.git (fetch)
origin	git://github.com/zaquestion/lab.git (push)
```

**Comment by zaquestion** [comment]
@ianfoo The confusion here is likely the expectation that `origin` always refers to the forked from project and never the user fork. This is the way hub operates. In fact, lab supports both paradigms.
Both of these are valid.
"upstream as remote"
```
origin git@gitlab.com:lab-testing/test
upstream git@gitlab.com:zaquestion/test
```
"user as remote"
```
origin git@gitlab.com:zaquestion/test
lab-testing git@gitlab.com:lab-testing/test
```

Essentially "user as remote" behaves the same as lab, exactly as your example above.

Users wishing to use the upstream mode have 2 options. 
clone a fork
```
lab clone lab-testing/test # fork of zaquestion/test
# yields these remotes
origin git@gitlab.com:lab-testing/test
upstream git@gitlab.com:zaquestion/test
```
fork with an argument
```
lab fork zaquestion/test
# yields these remotes, but creates the fork
origin git@gitlab.com:lab-testing/test
upstream git@gitlab.com:zaquestion/test
```
The above method has a similar issue (https://github.com/zaquestion/lab/issues/79) to this one

In this ticket `lab fork` should identify that the users "origin" points to a fork and add a new remote named "upstream" with the forked from repo. Hope that helps!
